package mrs.mapping;
// Generated Jun 15, 2017 9:53:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name="answer"
    
)
public class Answer  implements java.io.Serializable {


     private String ACode;
     private String QCode;
     private String answer;
     private Date createdTime;
     private Set<UserAnswer> userAnswers = new HashSet(0);

    public Answer() {
    }

	
    public Answer(String ACode, String QCode, String answer, Date createdTime) {
        this.ACode = ACode;
        this.QCode = QCode;
        this.answer = answer;
        this.createdTime = createdTime;
    }
    public Answer(String ACode, String QCode, String answer, Date createdTime, Set<UserAnswer> userAnswers) {
       this.ACode = ACode;
       this.QCode = QCode;
       this.answer = answer;
       this.createdTime = createdTime;
       this.userAnswers = userAnswers;
    }
   
     @Id 

    
    @Column(name="A_CODE", unique=true, nullable=false, length=10)
    public String getACode() {
        return this.ACode;
    }
    
    public void setACode(String ACode) {
        this.ACode = ACode;
    }

    
    @Column(name="Q_CODE", nullable=false, length=10)
    public String getQCode() {
        return this.QCode;
    }
    
    public void setQCode(String QCode) {
        this.QCode = QCode;
    }

    
    @Column(name="ANSWER", nullable=false, length=100)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_TIME", nullable=false, length=19)
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="answer")
    public Set<UserAnswer> getUserAnswers() {
        return this.userAnswers;
    }
    
    public void setUserAnswers(Set userAnswers) {
        this.userAnswers = userAnswers;
    }




}


