package mrs.mapping;
// Generated Jun 15, 2017 9:53:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalAuthority generated by hbm2java
 */
@Entity
@Table(name="local_authority"
   
)
public class LocalAuthority  implements java.io.Serializable {


     private String code;
     private String description;
     private String districtCode;
     private Set<SurveyData> surveyDatas = new HashSet(0);

    public LocalAuthority() {
    }

	
    public LocalAuthority(String code, String description, String districtCode) {
        this.code = code;
        this.description = description;
        this.districtCode = districtCode;
    }
    public LocalAuthority(String code, String description, String districtCode, Set<SurveyData> surveyDatas) {
       this.code = code;
       this.description = description;
       this.districtCode = districtCode;
       this.surveyDatas = surveyDatas;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="DISTRICT_CODE", nullable=false, length=10)
    public String getDistrictCode() {
        return this.districtCode;
    }
    
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="localAuthority")
    public Set<SurveyData> getSurveyDatas() {
        return this.surveyDatas;
    }
    
    public void setSurveyDatas(Set surveyDatas) {
        this.surveyDatas = surveyDatas;
    }




}


