package mrs.mapping;
// Generated Jun 15, 2017 9:53:30 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAnswer generated by hbm2java
 */
@Entity
@Table(name="user_answer"
    
)
public class UserAnswer  implements java.io.Serializable {


     private Integer id;
     private Answer answer;
     private Question question;
     private SurveyData surveyData;

    public UserAnswer() {
    }

    public UserAnswer(Answer answer, Question question, SurveyData surveyData) {
       this.answer = answer;
       this.question = question;
       this.surveyData = surveyData;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="A_CODE", nullable=false)
    public Answer getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(Answer answer) {
        this.answer = answer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Q_CODE", nullable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SURVEY_ID", nullable=false)
    public SurveyData getSurveyData() {
        return this.surveyData;
    }
    
    public void setSurveyData(SurveyData surveyData) {
        this.surveyData = surveyData;
    }




}


