package mrs.mapping;
// Generated Jun 15, 2017 9:53:30 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user"
)
public class User implements java.io.Serializable {

    private Integer keyid;
    private SocialMediaType socialMediaType;
    private UserType userType;
    private Integer userStatus;
    private String name;
    private String username;
    private String contactno;
    private String password;
    private int versionCode;
    private Date lastLogged;
    private Date createdTime;
    private Set<SurveyData> surveyDatas = new HashSet(0);

    public User() {
    }

    public User(Integer userStatus, SocialMediaType socialMediaType, UserType userType, String name, String username, String contactno, String password, int versionCode, Date lastLogged, Date createdTime) {
        this.socialMediaType = socialMediaType;
        this.userType = userType;
        this.name = name;
        this.username = username;
        this.contactno = contactno;
        this.password = password;
        this.versionCode = versionCode;
        this.lastLogged = lastLogged;
        this.createdTime = createdTime;
        this.userStatus = userStatus;
    }

    public User(Integer userStatus, SocialMediaType socialMediaType, UserType userType, String name, String username, String contactno, String password, int versionCode, Date lastLogged, Date createdTime, Set<SurveyData> surveyDatas) {
        this.socialMediaType = socialMediaType;
        this.userType = userType;
        this.name = name;
        this.username = username;
        this.contactno = contactno;
        this.password = password;
        this.versionCode = versionCode;
        this.lastLogged = lastLogged;
        this.createdTime = createdTime;
        this.surveyDatas = surveyDatas;
        this.userStatus = userStatus;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "KEYID", unique = true, nullable = false)
    public Integer getKeyid() {
        return this.keyid;
    }

    public void setKeyid(Integer keyid) {
        this.keyid = keyid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SOCIAL_MEDIA_TYPE", nullable = false)
    public SocialMediaType getSocialMediaType() {
        return this.socialMediaType;
    }

    public void setSocialMediaType(SocialMediaType socialMediaType) {
        this.socialMediaType = socialMediaType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "USER_TYPE", nullable = false)
    public UserType getUserType() {
        return this.userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    @Column(name = "NAME", nullable = false, length = 150)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "USERNAME", nullable = false, length = 100)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "CONTACTNO", nullable = false, length = 15)
    public String getContactno() {
        return this.contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    @Column(name = "PASSWORD", nullable = false, length = 150)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "VERSION_CODE", nullable = false)
    public int getVersionCode() {
        return this.versionCode;
    }

    public void setVersionCode(int versionCode) {
        this.versionCode = versionCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LAST_LOGGED", nullable = false, length = 19)
    public Date getLastLogged() {
        return this.lastLogged;
    }

    public void setLastLogged(Date lastLogged) {
        this.lastLogged = lastLogged;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_TIME", nullable = false, length = 19)
    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
    public Set<SurveyData> getSurveyDatas() {
        return this.surveyDatas;
    }

    public void setSurveyDatas(Set surveyDatas) {
        this.surveyDatas = surveyDatas;
    }

    @Column(name = "USER_STATUS",length = 2)
    public Integer getUserStatus() {
        return userStatus;
    }

    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

}
